name: Web Unit Tests (Jest)

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    web-unit-tests:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./web

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "npm"
                  cache-dependency-path: ./web/package-lock.json

            - name: Install dependencies
              run: npm ci

            - name: Run Jest unit tests
              run: npm run test:coverage

            - name: Upload Jest coverage report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: jest-coverage-report
                  path: web/coverage/
